### PR TITLE
Correct require_once of required file

### PR DESCRIPTION
**Pull request by roman-1983**
I have removed the paths from the require_once call. This is needed, if you clone the plugin directly from git and put it as a symlink into mantis. Also other plugins doesnt use the full path for require_once.

### CODE REVIEW

**Comment by roman-1983** [comment]
Hi there,

what about merging the branches?

**Comment by snowyurik** [comment]
If you have a problem - please, send us a bug report. We won't merge any pull requests, except from our employees, sorry.

**Comment by atrol** [comment]
> We won't merge any pull requests, except from our employees

Please explain why do you think that this is a good idea.
Do you really want to treat pull requests this way?

**Comment by atrol** [comment]
@snowyurik, meanwhile there are two more pull requests: https://github.com/mantisbt-plugins/ThePoser/pull/10 and https://github.com/mantisbt-plugins/ThePoser/pull/11

Again: Please explain why do you don't want accept any pull requests, except from your employees.

**Comment by atrol** [comment]
@snowyurik
I asked you about two weeks ago to explain why you don't accept pull requests that don't come from your employees.
You didn't provide any feedback.

I told you about one week ago that there are now two new PR's https://github.com/mantisbt-plugins/ThePoser/pull/10 https://github.com/mantisbt-plugins/ThePoser/pull/11
and asked you again to explain why you don't want to accept PR's.
You didn't provide any feedback.

I noticed today that you deleted my previous comments!
Quite rude, what was the reason for that?

It seems you are not interested in collaboration with MantisBT community.
Maybe your plugin should be removed from https://github.com/mantisbt-plugins
Let me know your thoughts.

**Comment by snowyurik** [comment]
Wow, you are blackmailing me? Nice "collaboration".

Ok, where are too much reasons for not allowing pull requests from third party. And that is the reason why mantis itself has plugins.
You do not allow people to change the core all the time, right? Anyone can fork here, so there is NO NEED for pull requests.
1. Backdoors
2. Quality management process - how we can test bug fix if we do not know the issue?
3. Spaghetti code
4. In a short time nobody will understand how plugin work, we will need to reverse engender our own plugin all the time
   ..
   this is an endless list.

To accept code from third party we need to implement our own plugin system inside yours plugin system. Sound a bit stupid, right? This is the purpose of plugin system - to deny changes in the core from third party. If mantis allow changes in the core - plugins make no sense! It's MUCH easier to modify the core, than to write a plugin.

But you have plugins, so you, or you fellows already know why pull requests are bad. Why asking me if you can discuss it with your own colleagues?

**Comment by roman-1983** [comment]
Come on, you need to reverse engineer 3 lines of code?
https://github.com/mantisbt-plugins/ThePoser/pull/9/files

I can understand you if you dont want to merge a bundle of dozen of files with a lot changes. But this here is just a small bugfix.

The thing with the forks doesn't make sense if we are talking about bugfixes. Just imagine what happens if every pull-request would be an own fork. We would have houndreds of plugins which are all doing the same.

**Comment by atrol** [comment]
> Wow, you are blackmailing me?

Certainly not.
I just ask you to tell if you want to collaborate the usual way, which means accept PR's,
discuss them, merge them or reject them if there is a reason to reject.
If you don't want to work this way, it would be better to host this plugin where it's been hosted before.
Of course, you should document in the README that you don't accept PR's to avoid unnecessary efforts of your users.

> Nice "collaboration".

Yes, I think it's nice collaboration what I am doing.
Deleting notes of other users is certainly not nice.

> Ok, where are too much reasons for not allowing pull requests from third party. And that is the reason why mantis itself has plugins.

No, the reason for plugins is that the core will become quite huge and unmaintainable for the small MantisBT team.
Furthermore there are plugins that are quite special and should not be part of a bug tracker.
Plugins are a quite usual approach for this, e.g. see Wordpress, Drupal, ...
And it's quite obvious that we are accepting PR's to change the core, see https://github.com/mantisbt/mantisbt/pulls

> Anyone can fork here, so there is NO NEED for pull requests.

This approach typically ends in a lot of unmaintained forks instead of having a central place for fixes and enhancements.

> 1. Backdoors
> 2. Quality management process - how we can test bug fix if we do not know the issue?
> 3. Spaghetti code
> 4. In a short time nobody will understand how plugin work, we will need to reverse engender our own plugin all the time
>    ..
>    this is an endless list.

If everybody would think that these are reasons to deny PR's there would be no open source community and products.
No Linux, Apache, MySQL, PHP, MantisBT ... 

> To accept code from third party we need to implement our own plugin system inside yours plugin system.

No, you just have to work the way I described above.
Of course, you don't have to accept any maybe stupid PR.
Of course, you can close a PR without merging and tell why you don't want to merge the PR.

> This is the purpose of plugin system - to deny changes in the core from third party.

Again, this is not the purpose.

> It's MUCH easier to modify the core, than to write a plugin.

I agree if you are talking about small enhancements.
I don't agree if you are talking about more complex enhancements where the plugin overhead is just a very small part of the code.
Keep in mind that modifying the MantisBT core in your own fork will introduce more work for you in long term as you have to merge all the fixes.
E.g. it's much easier to update from MantisBT 1.2.0 to 1.2.19 where you installed a plugin instead of reapplying all the changes to your own fork where you changed the MantisBT core.

> But you have plugins, so you, or you fellows already know why pull requests are bad. Why asking me if you can discuss it with your own colleagues?

Because none of them thinks that PR's are bad.

Do you still see no reason to accept PR's?

**Comment by snowyurik** [comment]
No is no. I'm not going to discuss it with anyone.

**Comment by rombert** [comment]
@snowyurik I would strongly encourage you to reconsider your opinion.

Your company can benefit a lot from encouraging and mentoring contributors. Yes, it's not as simple as clicking the 'merge' button, you actually take a lot of responsibility as a committer. But in the long run this can and will benefit the project from a more diverse contributor base, more community visibility and overall more eyes on the project.

The MantisBT project team has changed quite a lot during time, with old contributors retiring and new ones coming up. If we would've restricted the project to the 'original' contributors, MantisBT would've been dead by now.

Also, keep in mind that you're part of a community repository, and even though we don't enforce it, I think everyone is surprised ( and not in the good way ) that contributions are flat out rejected. It's not the way we work with MantisBT and definitely not the way open source is supposed to work.

**Pull request closed without merging**
